import { useEffect, useState } from "react";
import { getAdminHomePageContent, updateAdminHomePageContent, type HomePageContent } from "../services/adminHomePageService";

const blankCollection = { title: "New collection", description: "Collection description", image: "", href: "/shop" };
const blankAge = { shortLabel: "06", label: "New age group", description: "Description", age: "10–12Y" };
const blankHighlight = { icon: "sparkles", title: "New highlight", description: "Description" };
const Field = ({ label, value, onChange, large = false }: { label: string; value: string; onChange: (value: string) => void; large?: boolean }) => <label className="block"><span className="text-xs font-semibold text-black/60">{label}</span>{large ? <textarea value={value ?? ""} onChange={(e) => onChange(e.target.value)} rows={3} className="mt-1 w-full border border-black/15 px-3 py-2 text-sm" /> : <input value={value ?? ""} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full border border-black/15 px-3 py-2 text-sm" />}</label>;

export default function HomePageManager() {
  const [content, setContent] = useState<HomePageContent | null>(null);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const update = (section: string, key: string, value: string) => setContent((current: any) => ({ ...current, [section]: { ...current[section], [key]: value } }));
  const updateItem = (section: string, index: number, key: string, value: string) => setContent((current: any) => ({ ...current, [section]: { ...current[section], items: current[section].items.map((item: any, itemIndex: number) => itemIndex === index ? { ...item, [key]: value } : item) } }));
  const updateHighlight = (index: number, key: string, value: string) => setContent((current: any) => ({ ...current, highlights: current.highlights.map((item: any, itemIndex: number) => itemIndex === index ? { ...item, [key]: value } : item) }));
  const updateStat = (section: "hero" | "collections", index: number, key: string, value: string) => setContent((current: any) => ({ ...current, [section]: { ...current[section], stats: current[section].stats.map((item: any, itemIndex: number) => itemIndex === index ? { ...item, [key]: value } : item) } }));
  const removeItem = (section: string, index: number) => setContent((current: any) => ({ ...current, [section]: { ...current[section], items: current[section].items.filter((_: unknown, itemIndex: number) => itemIndex !== index) } }));
  useEffect(() => { void getAdminHomePageContent().then(setContent).catch((error) => setMessage(error.message)); }, []);
  async function save() { if (!content) return; try { setSaving(true); setMessage(""); setContent(await updateAdminHomePageContent(content)); setMessage("Homepage changes are live."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save homepage"); } finally { setSaving(false); } }
  if (!content) return <section className="mt-8 border border-black/10 bg-white p-6">Loading homepage editor…</section>;
  return <section className="mt-8 border border-black/10 bg-white"><div className="flex flex-col gap-3 border-b border-black/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#C9A227]">Storefront</p><h2 className="mt-1 text-xl font-semibold">Homepage content</h2><p className="mt-1 text-sm text-black/60">Edit all homepage text, links, images, and cards. Product cards are managed above in Product Management.</p></div><button type="button" onClick={() => void save()} disabled={saving} className="bg-[#0B0B0B] px-5 py-3 text-sm font-semibold text-white">{saving ? "Saving…" : "Save homepage"}</button></div>{message && <p className="mx-5 mt-5 border border-[#D4AF37]/40 bg-amber-50 px-3 py-2 text-sm">{message}</p>}<div className="space-y-8 p-5">
    <EditorTitle title="Hero banner" /><div className="grid gap-4 md:grid-cols-2"><Field label="Badge" value={content.hero.badge} onChange={(v) => update("hero", "badge", v)} /><Field label="Eyebrow" value={content.hero.eyebrow} onChange={(v) => update("hero", "eyebrow", v)} /><Field label="Heading" value={content.hero.title} onChange={(v) => update("hero", "title", v)} /><Field label="Gold heading" value={content.hero.accentTitle} onChange={(v) => update("hero", "accentTitle", v)} /><Field label="Hero image URL" value={content.hero.imageUrl} onChange={(v) => update("hero", "imageUrl", v)} /><Field label="Description" value={content.hero.description} large onChange={(v) => update("hero", "description", v)} /><Field label="Primary button text" value={content.hero.primaryLabel} onChange={(v) => update("hero", "primaryLabel", v)} /><Field label="Primary button link" value={content.hero.primaryHref} onChange={(v) => update("hero", "primaryHref", v)} /><Field label="Secondary button text" value={content.hero.secondaryLabel} onChange={(v) => update("hero", "secondaryLabel", v)} /><Field label="Secondary button link" value={content.hero.secondaryHref} onChange={(v) => update("hero", "secondaryHref", v)} /></div><ListTitle title="Hero statistics" onAdd={() => setContent((c: any) => ({ ...c, hero: { ...c.hero, stats: [...c.hero.stats, { value: "New", label: "Statistic" }] } }))} />{content.hero.stats.map((item: any, index: number) => <Card key={index} onRemove={() => setContent((c: any) => ({ ...c, hero: { ...c.hero, stats: c.hero.stats.filter((_: unknown, i: number) => i !== index) } }))}><Field label="Value" value={item.value} onChange={(v) => updateStat("hero", index, "value", v)} /><Field label="Label" value={item.label} onChange={(v) => updateStat("hero", index, "label", v)} /></Card>)}
    <ListTitle title="Highlights" onAdd={() => setContent((c: any) => ({ ...c, highlights: [...c.highlights, blankHighlight] }))} />{content.highlights.map((item: any, index: number) => <Card key={index} onRemove={() => setContent((c: any) => ({ ...c, highlights: c.highlights.filter((_: unknown, i: number) => i !== index) }))}><Field label="Title" value={item.title} onChange={(v) => updateHighlight(index, "title", v)} /><Field label="Description" value={item.description} onChange={(v) => updateHighlight(index, "description", v)} /><label><span className="text-xs font-semibold text-black/60">Icon</span><select value={item.icon} onChange={(e) => updateHighlight(index, "icon", e.target.value)} className="mt-1 w-full border border-black/15 px-3 py-2 text-sm"><option value="sparkles">Sparkles</option><option value="ruler">Ruler</option><option value="heart">Heart</option></select></label></Card>)}
    <EditorTitle title="Collections section" /><div className="grid gap-4 md:grid-cols-2"><Field label="Eyebrow" value={content.collections.eyebrow} onChange={(v) => update("collections", "eyebrow", v)} /><Field label="Heading" value={content.collections.title} onChange={(v) => update("collections", "title", v)} /><Field label="Description" value={content.collections.description} large onChange={(v) => update("collections", "description", v)} /><Field label="View-all label" value={content.collections.linkLabel} onChange={(v) => update("collections", "linkLabel", v)} /><Field label="View-all link" value={content.collections.linkHref} onChange={(v) => update("collections", "linkHref", v)} /></div><ListTitle title="Collection statistics" onAdd={() => setContent((c: any) => ({ ...c, collections: { ...c.collections, stats: [...c.collections.stats, { value: "New", label: "Statistic" }] } }))} />{content.collections.stats.map((item: any, index: number) => <Card key={index} onRemove={() => setContent((c: any) => ({ ...c, collections: { ...c.collections, stats: c.collections.stats.filter((_: unknown, i: number) => i !== index) } }))}><Field label="Value" value={item.value} onChange={(v) => updateStat("collections", index, "value", v)} /><Field label="Label" value={item.label} onChange={(v) => updateStat("collections", index, "label", v)} /></Card>)}<ListTitle title="Collection cards" onAdd={() => setContent((c: any) => ({ ...c, collections: { ...c.collections, items: [...c.collections.items, blankCollection] } }))} />{content.collections.items.map((item: any, index: number) => <Card key={index} onRemove={() => removeItem("collections", index)}><Field label="Title" value={item.title} onChange={(v) => updateItem("collections", index, "title", v)} /><Field label="Description" value={item.description} onChange={(v) => updateItem("collections", index, "description", v)} /><Field label="Image URL" value={item.image} onChange={(v) => updateItem("collections", index, "image", v)} /><Field label="Link" value={item.href} onChange={(v) => updateItem("collections", index, "href", v)} /></Card>)}
    <EditorTitle title="Age section" /><div className="grid gap-4 md:grid-cols-2"><Field label="Eyebrow" value={content.ages.eyebrow} onChange={(v) => update("ages", "eyebrow", v)} /><Field label="Heading" value={content.ages.title} onChange={(v) => update("ages", "title", v)} /><Field label="Description" value={content.ages.description} large onChange={(v) => update("ages", "description", v)} /><Field label="Footer text" value={content.ages.footer} large onChange={(v) => update("ages", "footer", v)} /></div><ListTitle title="Age-group rows" onAdd={() => setContent((c: any) => ({ ...c, ages: { ...c.ages, items: [...c.ages.items, blankAge] } }))} />{content.ages.items.map((item: any, index: number) => <Card key={index} onRemove={() => removeItem("ages", index)}><Field label="Number" value={item.shortLabel} onChange={(v) => updateItem("ages", index, "shortLabel", v)} /><Field label="Label" value={item.label} onChange={(v) => updateItem("ages", index, "label", v)} /><Field label="Description" value={item.description} onChange={(v) => updateItem("ages", index, "description", v)} /><Field label="Age / shop filter" value={item.age} onChange={(v) => updateItem("ages", index, "age", v)} /></Card>)}
    <EditorTitle title="Our story" /><div className="grid gap-4 md:grid-cols-2"><Field label="Eyebrow" value={content.story.eyebrow} onChange={(v) => update("story", "eyebrow", v)} /><Field label="Heading" value={content.story.title} onChange={(v) => update("story", "title", v)} /><Field label="Gold heading" value={content.story.accentTitle} onChange={(v) => update("story", "accentTitle", v)} /><Field label="Image URL" value={content.story.imageUrl} onChange={(v) => update("story", "imageUrl", v)} /><Field label="First paragraph" value={content.story.paragraphOne} large onChange={(v) => update("story", "paragraphOne", v)} /><Field label="Second paragraph" value={content.story.paragraphTwo} large onChange={(v) => update("story", "paragraphTwo", v)} /></div>
    <EditorTitle title="Call to action" /><div className="grid gap-4 md:grid-cols-2"><Field label="Eyebrow" value={content.cta.eyebrow} onChange={(v) => update("cta", "eyebrow", v)} /><Field label="Heading" value={content.cta.title} onChange={(v) => update("cta", "title", v)} /><Field label="Description" value={content.cta.description} large onChange={(v) => update("cta", "description", v)} /><Field label="Button text" value={content.cta.buttonLabel} onChange={(v) => update("cta", "buttonLabel", v)} /><Field label="Button link" value={content.cta.buttonHref} onChange={(v) => update("cta", "buttonHref", v)} /></div>
  </div></section>;
}
const EditorTitle = ({ title }: { title: string }) => <h3 className="border-b border-black/10 pb-2 text-lg font-semibold">{title}</h3>;
const ListTitle = ({ title, onAdd }: { title: string; onAdd: () => void }) => <div className="flex items-center justify-between"><h3 className="text-lg font-semibold">{title}</h3><button type="button" onClick={onAdd} className="border border-black/20 px-3 py-2 text-xs font-semibold">+ Add</button></div>;
const Card = ({ children, onRemove }: { children: React.ReactNode; onRemove: () => void }) => <div className="relative grid gap-3 border border-black/10 bg-[#fffdf9] p-4 md:grid-cols-2"><button type="button" onClick={onRemove} className="absolute right-2 top-2 text-xs font-semibold text-red-700">Remove</button><div className="col-span-full pr-16" />{children}</div>;
