import { API_BASE_URL } from "../config/api";

export type HomePageContent = {
  hero: { badge: string; eyebrow: string; title: string; accentTitle: string; description: string; imageUrl: string; primaryLabel: string; primaryHref: string; secondaryLabel: string; secondaryHref: string; stats: { value: string; label: string }[] };
  highlights: { icon: string; title: string; description: string }[];
  collections: { eyebrow: string; title: string; description: string; linkLabel: string; linkHref: string; stats: { value: string; label: string }[]; items: { title: string; description: string; image: string; href: string }[] };
  ages: { eyebrow: string; title: string; description: string; footer: string; linkLabel: string; linkHref: string; items: { shortLabel: string; label: string; description: string; age: string }[] };
  story: { eyebrow: string; title: string; accentTitle: string; imageUrl: string; paragraphOne: string; paragraphTwo: string; linkLabel: string; linkHref: string };
  cta: { eyebrow: string; title: string; description: string; buttonLabel: string; buttonHref: string };
};

export const DEFAULT_HOME_CONTENT: HomePageContent = {
  hero: { badge: "New festive edit", eyebrow: "Tradition · Comfort · Elegance", title: "Little girls,", accentTitle: "timeless traditions.", description: "Discover beautiful South Indian traditional wear crafted for little girls, from everyday cottons to festive pattu styles.", imageUrl: "/images/hero/hero-banner.png", primaryLabel: "Shop Collection", primaryHref: "/shop", secondaryLabel: "Explore Pattu", secondaryHref: "/shop?category=Pattu%20Frocks", stats: [{ value: "100+", label: "Happy Customers" }, { value: "7 Days", label: "Easy Returns" }] },
  highlights: [{ icon: "sparkles", title: "Made for little moments", description: "Festive details with an easy, playful feel." }, { icon: "ruler", title: "A fit for every chapter", description: "Thoughtful styles from newborn through 10 years." }, { icon: "heart", title: "Easy returns", description: "A seven-day return window for extra peace of mind." }],
  collections: { eyebrow: "Our Collections", title: "Featured Collections", description: "Curated collections of traditional South Indian wear for every occasion and age group.", linkLabel: "View All Collections", linkHref: "/shop", stats: [{ value: "500+", label: "Premium Products" }, { value: "NB–10Y", label: "Age Groups Covered" }], items: [{ title: "Cotton Frocks", description: "Soft, comfortable styles for everyday elegance.", image: "/images/products/traditional-cotton-frock.jpg", href: "/shop?category=Cotton%20Frocks" }, { title: "Pattu Frocks", description: "Festive silhouettes crafted for special moments.", image: "/images/products/festive-pattu-frock.jpg", href: "/shop?category=Pattu%20Frocks" }, { title: "Cotton Pavadai", description: "Timeless traditional comfort for little girls.", image: "/images/products/classic-cotton-pavadai.jpg", href: "/shop?category=Cotton%20Pavadai" }, { title: "Pattu Pavadai", description: "Graceful festive dressing with a traditional touch.", image: "/images/products/festive-pattu-pavadai.jpg", href: "/shop?category=Pattu%20Pavadai" }] },
  ages: { eyebrow: "Shop by Age", title: "Beautiful traditions, made for every age.", description: "From their very first celebrations to their growing years, discover thoughtfully chosen styles designed for every little milestone.", footer: "Designed around childhood, comfort, and the timeless beauty of South Indian tradition.", linkLabel: "Explore All Styles", linkHref: "/shop", items: [{ shortLabel: "NB", label: "Newborn", description: "First little traditions", age: "0–3M" }, { shortLabel: "01", label: "Tiny Tots", description: "Soft everyday styles", age: "0–2Y" }, { shortLabel: "02", label: "Little Ones", description: "Playful festive looks", age: "2–4Y" }, { shortLabel: "03", label: "Growing Girls", description: "Beautiful celebration wear", age: "4–6Y" }, { shortLabel: "04", label: "Young Girls", description: "Elegant traditional styles", age: "6–8Y" }, { shortLabel: "05", label: "Big Girls", description: "Timeless festive elegance", age: "8–10Y" }] },
  story: { eyebrow: "Our Story", title: "Tradition made for", accentTitle: "little moments.", imageUrl: "/images/story/our-story.jpg", paragraphOne: "We believe traditional clothing should feel as beautiful as the memories created while wearing it. Our collection brings together comfortable fabrics, graceful details and timeless South Indian styles for little girls.", paragraphTwo: "From everyday cotton frocks to festive pattu pavadai, each style is chosen to celebrate childhood while keeping tradition close.", linkLabel: "Discover the Collection", linkHref: "/shop" },
  cta: { eyebrow: "Celebrate Every Little Moment", title: "Dress them in traditions they'll always remember.", description: "Discover beautiful traditional girlswear made for festivals, celebrations, family gatherings, and precious childhood memories.", buttonLabel: "Shop Collection", buttonHref: "/shop" },
};

export async function getHomePageContent(): Promise<HomePageContent> {
  const response = await fetch(`${API_BASE_URL}/homepage`);
  const result = await response.json().catch(() => null) as { success?: boolean; data?: HomePageContent } | null;
  if (!response.ok || !result?.success || !result.data) throw new Error("Failed to load homepage content");
  return result.data;
}
